apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: balloon-race
  labels:
    app: balloon-race

spec:
  replicas: 1
  selector:
    matchLabels:
      app: balloon-race
  template:
    metadata:
      labels:
        app: balloon-race
    spec:
      containers:
        - name: balloon-race
          image: ghcr.io/calfur/balloon-race:1f02b751ec2fb420ffe95057547eaa499d7457b1
          ports:
            - name: web
              containerPort: 80
