services:
  reverse-proxy:
    image: ghcr.io/calfur/calfur-dev/reverse-proxy:latest
    container_name: reverse-proxy
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - "443:443"
    networks:
      - webnet
    depends_on:
      - certbot
      - certbot-init

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: /bin/sh -c 'trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot --post-hook "nginx -s reload"; sleep 12h; done'

  certbot-init:
    image: certbot/certbot
    container_name: certbot-init
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: /bin/sh -c 'if [ ! -f /etc/letsencrypt/live/calfur.dev/fullchain.pem ]; then certbot certonly --webroot -w /var/www/certbot --email robin.nater@hotmail.com --agree-tos --no-eff-email -d calfur.dev -d *.calfur.dev; fi'

networks:
  webnet:
    external: true
