services:
  reverse-proxy:
    image: ghcr.io/calfur/calfur-dev/reverse-proxy:latest
    container_name: reverse-proxy
    volumes:
      - ./certbot/conf:/etc/ssl/:ro
      - ./certbot/www:/var/www/certbot/:ro
    ports:
      - "443:443"
    restart: always
    networks:
      - webnet

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/ssl/:rw
      - ./certbot/www:/var/www/certbot/:rw
    entrypoint: /bin/sh -c 'trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot --post-hook "echo reload nginx here"; sleep 12h; done'
    depends_on:
      - reverse-proxy

  certbot-init:
    image: certbot/certbot:latest
    container_name: certbot-init
    volumes:
      - ./certbot/conf:/etc/ssl/:rw
      - ./certbot/www:/var/www/certbot/:rw
    entrypoint: /bin/sh -c 'if [ ! -f /etc/ssl/live/calfur.dev/fullchain.pem ]; then certbot certonly --webroot --webroot-path /var/www/certbot/ -d calfur.dev -d *.calfur.dev --post-hook "echo reload nginx here"; fi'
    ports:
      - "80:80"
    depends_on:
      - reverse-proxy

networks:
  webnet:
    external: true
