apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: killer-frontend

spec:
  ports:
    - protocol: TCP
      name: web
      port: 80
      targetPort: 80
  selector:
    app: killer-frontend
