apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: killer-frontend
  labels:
    app: killer-frontend

spec:
  replicas: 1
  selector:
    matchLabels:
      app: killer-frontend
  template:
    metadata:
      labels:
        app: killer-frontend
    spec:
      containers:
        - name: killer-frontend
          image: ghcr.io/calfur/killer-frontend:5d71f86f7be94b912b8eaa50a42a149656c4b81d
          ports:
            - name: web
              containerPort: 80
