apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: killer-frontend
  labels:
    app: killer-frontend

spec:
  replicas: 1
  selector:
    matchLabels:
      app: killer-frontend
  template:
    metadata:
      labels:
        app: killer-frontend
    spec:
      containers:
        - name: killer-frontend
          image: ghcr.io/calfur/killer-frontend:552329630debcf843ffa0e4d81850eec37ff93b9
          ports:
            - name: web
              containerPort: 80
