apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: traefik
  labels:
    app: traefik

spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      containers:
        - name: traefik
          image: traefik:v3.0
          args:
            - --api.insecure
            - --accesslog
            - --entrypoints.web.Address=:8000
            - --entrypoints.websecure.Address=:4443
            - --providers.kubernetescrd
            - --certificatesresolvers.myresolver.acme.tlschallenge
            - --certificatesresolvers.myresolver.acme.email=$(TRAEFIK_ACME_EMAIL)
            - --certificatesresolvers.myresolver.acme.storage=/data/acme.json
          ports:
            - name: web
              containerPort: 8000
            - name: websecure
              containerPort: 4443
          volumeMounts:
            - name: traefik-storage
              mountPath: /data
          env:
            - name: TRAEFIK_ACME_EMAIL
              valueFrom:
                secretKeyRef:
                  name: traefik-acme-email
                  key: email
      volumes:
        - name: traefik-storage
          persistentVolumeClaim:
            claimName: traefik-pvc
