labels:
  - includeSelectors: false
    includeTemplates: true
    pairs:
      app.kubernetes.io/part-of: traefik
      calfur.dev/managed-by: calfur-dev
resources:
  - ./external/kubernetes-crd-definition-v1.yml
  - ./external/kubernetes-crd-rbac.yml
  - 00-volumes.yml
  - 01-account.yml
  - 02-service.yml
  - 03-deployment.yml
