apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: volleyballnacht
  labels:
    app: volleyballnacht

spec:
  replicas: 1
  selector:
    matchLabels:
      app: volleyballnacht
  template:
    metadata:
      labels:
        app: volleyballnacht
    spec:
      containers:
        - name: volleyballnacht
          image: ghcr.io/jubla-nz/volleyball-nacht:bd8fa4bd65186ecf39c7af4ab4a30845fcb2b8bd
          ports:
            - name: web
              containerPort: 80
      imagePullSecrets:
        - name: ghcr-secret
