apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: volleyballnacht
  labels:
    app: volleyballnacht

spec:
  replicas: 1
  selector:
    matchLabels:
      app: volleyballnacht
  template:
    metadata:
      labels:
        app: volleyballnacht
    spec:
      containers:
        - name: volleyballnacht
          image: ghcr.io/jubla-nz/volleyball-nacht:ba2c7953fed440136e65f07a762b0be36a50ea76
          ports:
            - name: web
              containerPort: 80
      imagePullSecrets:
        - name: ghcr-secret
