apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: volleyballnacht
  labels:
    app: volleyballnacht

spec:
  replicas: 1
  selector:
    matchLabels:
      app: volleyballnacht
  template:
    metadata:
      labels:
        app: volleyballnacht
    spec:
      automountServiceAccountToken: false
      containers:
        - name: volleyballnacht
          image: ghcr.io/jubla-nz/volleyball-nacht:ea286ce5f01b1b3db0134aa7b9d81d58b6cf3f58
          ports:
            - name: web
              containerPort: 80
      imagePullSecrets:
        - name: ghcr-secret
