apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: volleyballnacht
  labels:
    app: volleyballnacht

spec:
  replicas: 1
  selector:
    matchLabels:
      app: volleyballnacht
  template:
    metadata:
      labels:
        app: volleyballnacht
    spec:
      automountServiceAccountToken: false
      containers:
        - name: volleyballnacht
          image: ghcr.io/jubla-nz/volleyball-nacht:c83660d9307d19c8cc9d489ee17cc02d5a88ad40
          ports:
            - name: web
              containerPort: 80
      imagePullSecrets:
        - name: ghcr-secret
