apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: volleyballnacht
  labels:
    app: volleyballnacht

spec:
  replicas: 1
  selector:
    matchLabels:
      app: volleyballnacht
  template:
    metadata:
      labels:
        app: volleyballnacht
    spec:
      containers:
        - name: volleyballnacht
          image: ghcr.io/jubla-nz/volleyball-nacht:a7fd832ec981f48b3c73f6424f26b316f3c6987e
          ports:
            - name: web
              containerPort: 80
      imagePullSecrets:
        - name: ghcr-secret
