apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: fondueplausch
  labels:
    app: fondueplausch

spec:
  replicas: 1
  selector:
    matchLabels:
      app: fondueplausch
  template:
    metadata:
      labels:
        app: fondueplausch
    spec:
      containers:
        - name: fondueplausch
          image: ghcr.io/jubla-nz/fondue-plausch:5265ca4d79f0c8d3200896a08fabcc3a6a36bd13
          ports:
            - name: web
              containerPort: 80
      imagePullSecrets:
        - name: ghcr-secret
