apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: fondueplausch
  labels:
    app: fondueplausch

spec:
  replicas: 1
  selector:
    matchLabels:
      app: fondueplausch
  template:
    metadata:
      labels:
        app: fondueplausch
    spec:
      containers:
        - name: fondueplausch
          image: ghcr.io/jubla-nz/fondue-plausch:56ce35785a0bd7b619089aafbb1f257999e576cd
          ports:
            - name: web
              containerPort: 80
      imagePullSecrets:
        - name: ghcr-secret
