apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: party-battle-backend-catchall

spec:
  ports:
    - protocol: TCP
      name: api
      port: 80
      targetPort: 80
  selector:
    app: party-battle-backend-catchall
