apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: star-wars-bild-countdown
  labels:
    app: star-wars-bild-countdown

spec:
  replicas: 1
  selector:
    matchLabels:
      app: star-wars-bild-countdown
  template:
    metadata:
      labels:
        app: star-wars-bild-countdown
    spec:
      containers:
        - name: star-wars-bild-countdown
          image: ghcr.io/calfur/star-wars-bild-countdown:c6eff339584a395b47e652e13a8c44d59b845dd0
          ports:
            - name: web
              containerPort: 5000
