apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: homepage
  labels:
    app: homepage

spec:
  replicas: 1
  selector:
    matchLabels:
      app: homepage
  template:
    metadata:
      labels:
        app: homepage
    spec:
      containers:
        - name: homepage
          image: ghcr.io/calfur/homepage:a5c25013ec48398c6db7880895bad65c945c4cb0
          ports:
            - name: web
              containerPort: 3000 