apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: homepage
  labels:
    app: homepage

spec:
  replicas: 1
  selector:
    matchLabels:
      app: homepage
  template:
    metadata:
      labels:
        app: homepage
    spec:
      containers:
        - name: homepage
          image: ghcr.io/calfur/homepage:773b2f567ee6defd1625ecd76e9458c1f79f9ffc
          ports:
            - name: web
              containerPort: 3000 