apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  namespace: default
  name: ingressroute-jetski
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`jetski.calfur.dev`)
      kind: Rule
      services:
        - name: jetski
          port: 80
    - match: Host(`www.jetski.calfur.dev`)
      kind: Rule
      middlewares:
        - name: redirect-www-to-root-jetski
      services:
        - name: jetski
          port: 80
  tls:
    certResolver: myresolver
    domains:
      - main: jetski.calfur.dev
        sans:
          - www.jetski.calfur.dev
