apiVersion: v1
kind: Service
metadata:
  name: reverse-proxy
spec:
  type: LoadBalancer
  selector:
    app: traefik
  ports:
    - protocol: TCP
      name: web
      port: 8000
    - protocol: TCP
      name: websecure
      port: 4443
