apiVersion: v1
kind: Service
metadata:
  name: reverse-proxy
spec:
  type: LoadBalancer
  selector:
    app: reverse-proxy
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: 80
    - name: websecure
      protocol: TCP
      port: 443
      targetPort: 443
