apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: killer
  labels:
    app: killer

spec:
  replicas: 1
  selector:
    matchLabels:
      app: killer
  template:
    metadata:
      labels:
        app: killer
    spec:
      containers:
        - name: killer
          image: ghcr.io/calfur/killer:0e827a41a5f5fd7331c5fce730d4752becefc521
          ports:
            - name: web
              containerPort: 5000
