apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: killer
  labels:
    app: killer

spec:
  replicas: 1
  selector:
    matchLabels:
      app: killer
  template:
    metadata:
      labels:
        app: killer
    spec:
      containers:
        - name: killer
          image: ghcr.io/calfur/killer:7ec724f896b53071b1ad8ad416a4255bd8b3997c
          ports:
            - name: web
              containerPort: 80
