apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: killer
  labels:
    app: killer

spec:
  replicas: 1
  selector:
    matchLabels:
      app: killer
  template:
    metadata:
      labels:
        app: killer
    spec:
      containers:
        - name: killer
          image: ghcr.io/calfur/killer:225750e43dc7c86ba1dbac0cafe19f67903f2d1b
          ports:
            - name: web
              containerPort: 5000
