apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: killer
  labels:
    app: killer

spec:
  replicas: 1
  selector:
    matchLabels:
      app: killer
  template:
    metadata:
      labels:
        app: killer
    spec:
      containers:
        - name: killer
          image: ghcr.io/calfur/killer:fbc6da10df6acee01349782f7e5bccd7b2500e81
          ports:
            - name: web
              containerPort: 5000
