apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: killer
  labels:
    app: killer

spec:
  replicas: 1
  selector:
    matchLabels:
      app: killer
  template:
    metadata:
      labels:
        app: killer
    spec:
      containers:
        - name: killer
          image: ghcr.io/calfur/killer:38f01e5af93441904a2a01b5221ba32fad9b86d4
          ports:
            - name: web
              containerPort: 5000
