name: Deploy to Kubernetes

on:
  push:
    branches:
      - master
  workflow_dispatch:
  repository_dispatch:
    types: [deploy]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Copy Kubernetes manifests to the server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "./kubernetes/*"
        target: "/opt/GitHubAction/"

    - name: Apply Kubernetes manifests on the server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          set -e

          echo "::group::Creating Docker registry secret"
          kubectl create secret docker-registry ghcr-secret-q-swiper \
            --docker-server=ghcr.io \
            --docker-username=${GITHUB_ACTOR} \
            --docker-password=${GH_PAT_PACKAGES_READ} \
            --docker-email=robin.nater@hotmail.com \
            --dry-run=client -o yaml | kubectl apply -f -
          echo "::endgroup::"

          echo "::group::Applying Kubernetes manifests"
          kubectl apply -k /opt/GitHubAction/kubernetes/traefik
          kubectl apply -k /opt/GitHubAction/kubernetes/pannenstreifen
          kubectl apply -k /opt/GitHubAction/kubernetes/q-swiper
          kubectl apply -k /opt/GitHubAction/kubernetes/balloon
          echo "::endgroup::"

          echo "::group::Cleaning up"
          rm -rf /opt/GitHubAction/
          echo "::endgroup::"
