name: Deploy to Kubernetes

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Copy Kubernetes manifests to the server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "./kubernetes/*"
        target: "/opt/GitHubAction/"

    - name: Apply Kubernetes manifests on the server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          set -e
          kubectl apply -f /opt/GitHubAction/kubernetes/00-account.yml
          kubectl apply -f /opt/GitHubAction/kubernetes/00-role.yml
          kubectl apply -f /opt/GitHubAction/kubernetes/01-role-binding.yml
          kubectl apply -f /opt/GitHubAction/kubernetes/02-traefik-deployment.yml
          kubectl apply -f /opt/GitHubAction/kubernetes/02-traefik-service.yml
          kubectl apply -f /opt/GitHubAction/kubernetes/03-pannenstreifen-website-deployment.yml
          kubectl apply -f /opt/GitHubAction/kubernetes/03-pannenstreifen-website-service.yml
          kubectl apply -f /opt/GitHubAction/kubernetes/04-pannenstreifen-website-ingress.yml
          rm -rf /opt/GitHubAction/
