name: Deploy to Kubernetes

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up K8s context
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config

    - name: Apply Kubernetes manifests
      run: |
        kubectl apply -f kubernetes/traefik-deployment.yaml
        kubectl apply -f kubernetes/traefik-service.yaml
        kubectl apply -f kubernetes/pannenstreifen-website-deployment.yaml
        kubectl apply -f kubernetes/pannenstreifen-website-service.yaml
        kubectl apply -f kubernetes/pannenstreifen-website-ingress.yaml
