name: Deploy to Kubernetes

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up K8s context
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config

    - name: Apply Kubernetes manifests
      run: |
        kubectl apply -f kubernetes/00-account.yml
        kubectl apply -f kubernetes/00-role.yml
        kubectl apply -f kubernetes/01-role-binding.yml
        kubectl apply -f kubernetes/02-traefik-deployment.yml
        kubectl apply -f kubernetes/02-traefik-service.yml
        kubectl apply -f kubernetes/03-pannenstreifen-website-deployment.yml
        kubectl apply -f kubernetes/03-pannenstreifen-website-ingress.yml
        kubeclt apply -f kubernetes/03-pannenstreifen-website-service.yml
