name: Update Jetski Image

on:
  repository_dispatch:
    types: [new-jetski-image]

jobs:
  call-template:
    uses: ./.github/workflows/update-image-template.yml
    with:
      image_version: ${{ github.event.client_payload.image_version }}
      image_name: ghcr.io/calfur/jetski
      file_path: ./kubernetes/jetski/02-deployment.yml
      trigger_deploy: true
