name: Update Balloon Race Image

on:
  repository_dispatch:
    types: [new-balloon-race-image]

jobs:
  call-template:
    uses: ./.github/workflows/templates/update-image.yml
    with:
      image_version: ${{ github.event.client_payload.image_version }}
      image_name: ghcr.io/calfur/balloon-race
      file_path: ./kubernetes/balloon-race/02-deployment.yml
