name: Update Killer Image

on:
  repository_dispatch:
    types: [new-killer-image]

jobs:
  call-template:
    uses: ./.github/workflows/update-image-template.yml
    with:
      image_version: ${{ github.event.client_payload.image_version }}
      image_name: ghcr.io/calfur/killer
      file_path: ./kubernetes/killer/02-deployment.yml
      trigger_deploy: true
