name: Update Q-Swiper Image

on:
  repository_dispatch:
    types: [new-q-swiper-image]

jobs:
  call-template:
    uses: ./.github/workflows/update-image-template.yml
    with:
      image_version: ${{ github.event.client_payload.image_version }}
      image_name: ghcr.io/q-swiper/map-generator
      file_path: ./kubernetes/q-swiper/02-deployment.yml
