name: Update Image Version

on:
  workflow_call:
    inputs:
      image_version:
        required: true
        type: string
      image_name:
        required: true
        type: string
      file_path:
        required: true
        type: string

jobs:
  update-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create a new branch
        run: |
          git checkout -b update-${{ inputs.image_name }}-${{ inputs.image_version }}

      - name: Push new branch
        run: |
          git push --set-upstream origin update-${{ inputs.image_name }}-${{ inputs.image_version }}

      - name: Update Image Version
        run: |
          sed -i "s|ghcr.io/.*/.*:.*|${{ inputs.image_name }}:${{ inputs.image_version }}|g" ${{ inputs.file_path }}

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "Update image version of ${{ inputs.image_name }} to ${{ inputs.image_version }}"
          add: ${{ inputs.file_path }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: update-${{ inputs.image_name }}-${{ inputs.image_version }}
          title: "Update image version of ${{ inputs.image_name }} to ${{ inputs.image_version }}"
          body: "This PR updates the image version of ${{ inputs.image_name }} to ${{ inputs.image_version }}."
          base: master
          draft: false

      - name: Merge the PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pullRequests = await github.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              head: `${context.repo.owner}:update-${{ inputs.image_name }}-${{ inputs.image_version }}`
            });

            if (pullRequests.data.length > 0) {
              const pr = pullRequests.data[0];
              await github.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number
              });
            }

      - name: Trigger deployment pipeline
        uses: peter-evans/repository-dispatch@v3
        with:
          event-type: deploy
