apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: killer-backend

spec:
  ports:
    - protocol: TCP
      name: backend
      port: 80
      targetPort: 5000
  selector:
    app: killer-backend
