apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: killer-backend
  labels:
    app: killer-backend

spec:
  replicas: 1
  selector:
    matchLabels:
      app: killer-backend
  template:
    metadata:
      labels:
        app: killer-backend
    spec:
      containers:
        - name: killer-backend
          image: ghcr.io/calfur/killer-backend:03e1537c91f74bd6b215f36464adaed9a56f14a7
          ports:
            - name: backend
              containerPort: 5000
